server:
  port: 8100
  servlet:
    context-path: /${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://192.168.44.56:8080/eureka
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    status-page-url-path: /${spring.application.name}

spring:
  application:
      name: elk
  datasource:
    driver-class-name: com.informix.jdbc.IfxDriver
    username: cloud_sys
    password: ylz2018
    url: jdbc:informix-sqli://192.168.44.86:9088/cloud_sys:INFORMIXSERVER=gbaseserver;DB_LOCALE=zh_CN.utf8;CLIENT_LOCALE=zh_CN.utf8;NEWCODESET=UTF8,utf8,57372;GL_USEGLU=1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  http:
    encoding:
      force: true
  data:
    elasticsearch:
      cluster-name: ylz
      cluster-nodes: 192.168.44.88:9300

logging:
  level:
    com.ylz.log.elk.manage.dao.mapper: debug

feign:
  hystrix:
    enabled: true

# 单点登录 对接
ms:
  admin:
    auth:
      # 访问单点登入的url地址
      serverName: http://192.168.21.155:${server.port}/elk
      shiro:
        logoutUrl: /logout.html
        successUrl: /index.html
        unauthorizedUrl: /500.html
      cas:
        prefixUrl: http://wwwdemo.msyos.com/adminAuth
        logoutUrl: http://wwwdemo.msyos.com/adminAuth/logout
        changePwdUrl: http://wwwdemo.msyos.com/adminAuth/oauth2.0