server:
  port: 12500
  servlet:
    context-path: /${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://10.1.71.21:10800/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    status-page-url-path: /${spring.application.name}

spring:
  application:
      name: elk
  datasource:
    driver-class-name: com.informix.jdbc.IfxDriver
    url: jdbc:informix-sqli://10.1.70.57:1521/log_link:INFORMIXSERVER=gbase;DB_LOCALE=zh_CN.utf8;CLIENT_LOCALE=zh_CN.utf8;NEWCODESET=UTF8,utf8,57372;GL_USEGLU=1
    username: informix
    password: zwxxglc1264
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  http:
    encoding:
      force: true
  data:
    elasticsearch:
      cluster-name: esCluster
      cluster-nodes: node-2

logging:
  level:
    com.ylz.log.elk.manage.dao.mapper: debug

feign:
  hystrix:
    enabled: true

# 单点登录 对接
ms:
  admin:
    auth:
      # 访问单点登入的url地址
      serverName: http://10.1.71.21:${server.port}/elk
      shiro:
        logoutUrl: /logout.html
        successUrl: /index.html
        unauthorizedUrl: /500.html
      cas:
        prefixUrl: http://10.1.71.23:11300/adminAuth
        logoutUrl: http://10.1.71.23:11300/adminAuth/logout
        changePwdUrl: http://10.1.71.23:11300/adminAuth/oauth2.0