spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ylzinfo
    url: jdbc:mysql://192.168.43.33:3306/elk?useSSL=false&allowMultiQueries=true
#  redis:
#    host: localhost
#  session:
#      store-type: redis
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  http:
    encoding:
      force: true
  data:
    elasticsearch:
      cluster-name: ylz
      cluster-nodes: 192.168.44.88:9300

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-conf.xml

pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.ylz.log.elk.manage.dao.mapper: debug

# 单点登录
ms:
  admin:
    auth:
      # 访问单点登入的url地址
      serverName: http://localhost:${server.port}/microservice-management
      shiro:
        logoutUrl: /logout.html
        successUrl: /index.html
        unauthorizedUrl: /500.html
      cas:
        logoutUrl: http://wwwdemo.msyos.com/adminAuth/logout
        changePwdUrl: http://wwwdemo.msyos.com/adminAuth/oauth2.0
      oauth:
        urlPrefix: http://wwwdemo.msyos.com/adminAuth/oauth2.0
        clientId: MicroServiceManagement
        clientSecret: Ylzinfo@pt
        successUrl: /index.html
