server:
  port: 8100
  servlet:
    context-path: /${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://192.168.44.56:8080/eureka
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    status-page-url-path: /${spring.application.name}

# 单点登录 对接
ms:
  admin:
    auth:
      # 访问单点登入的url地址
      serverName: http://wwwdemo.msyos.com/elk/
      shiro:
        logoutUrl: /logout.html
        successUrl: /index.html
        unauthorizedUrl: /500.html
      cas:
        logoutUrl: http://wwwdemo.msyos.com/adminAuth/logout
        changePwdUrl: http://wwwdemo.msyos.com/adminAuth/oauth2.0
      oauth:
        urlPrefix: http://wwwdemo.msyos.com/adminAuth/oauth2.0
        clientId: elk
        clientSecret: Ylzinfo@pt
        successUrl: /index.html