spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shiro?useSSL=false&allowMultiQueries=true
#  redis:
#    host: localhost
#  session:
#      store-type: redis
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  http:
    encoding:
      force: true
  data:
    elasticsearch:
      cluster-name: ylz
      cluster-nodes: 192.168.44.86:9300

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-conf.xml

pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 8081
logging:
  level:
    com.ylz.log.elk.manage.dao.mapper: debug


